/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlythuvien;

import java.awt.Desktop;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;
import org.apache.poi.openxml4j.opc.OPCPackage;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.apache.poi.ss.usermodel.DateUtil;
import org.apache.poi.ss.util.NumberToTextConverter;
import org.apache.poi.xwpf.usermodel.IBodyElement;
import org.apache.poi.xwpf.usermodel.TableRowAlign;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;
import org.apache.poi.xwpf.usermodel.XWPFTable;
import org.apache.poi.xwpf.usermodel.XWPFTableRow;

/**
 *
 * @author Đình Phúc
 */
public class QuanLyNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyNhanVien
     */
    DefaultTableModel model;
    MyConnect myConnect = new MyConnect();
    Connection conn = myConnect.connect();
    PreparedStatement ps = null;
    int rowID = 0;
    boolean fileOut = true;

    public QuanLyNhanVien() {
        initComponents();
        model = (DefaultTableModel) Table1.getModel();
        removeAllRow();
        showTable(getListNV());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        maNV = new javax.swing.JTextField();
        tenNV = new javax.swing.JTextField();
        ngaySinh = new javax.swing.JTextField();
        gT = new javax.swing.JTextField();
        diaChi = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        sDT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        comboTimKiem = new javax.swing.JComboBox<>();
        xuatNV = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        timKiem = new javax.swing.JTextField();
        nhap = new javax.swing.JButton();
        AddToDB = new javax.swing.JButton();
        seeAll = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        TKNV = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table2 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();

        setTitle("LÊ ĐÌNH PHÚC _ 20163184 _ Quản Lý Nhân Viên");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jDesktopPane2.setBackground(new java.awt.Color(46, 78, 104));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mã Nhân Viên");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tên Nhân Viên");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ngày Sinh");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Giới Tính");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SĐT");

        maNV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        tenNV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        ngaySinh.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ngaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngaySinhActionPerformed(evt);
            }
        });

        gT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        gT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gTActionPerformed(evt);
            }
        });

        diaChi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        diaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaChiActionPerformed(evt);
            }
        });

        email.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        sDT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Địa Chỉ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlythuvien/icon/ínert.png"))); // NOI18N
        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlythuvien/icon/sửa.png"))); // NOI18N
        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlythuvien/icon/remove.png"))); // NOI18N
        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Table1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "         Mã Nhân Viên", "     Tên Nhân Viên", "     Ngày Sinh", "       Giới Tính", "           Địa Chỉ", "         Email  ", "              SĐT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table1.setComponentPopupMenu(jPopupMenu1);
        Table1.setRowHeight(26);
        Table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table1);

        comboTimKiem.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        comboTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tìm Kiếm Theo Mã Nhân Viên", "Tìm Kiếm Theo Tên Nhân Viên", "Tìm Kiếm Theo Địa Chỉ", "Tìm Kiếm Theo Email", "Tìm Kiếm Theo SĐT" }));
        comboTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTimKiemActionPerformed(evt);
            }
        });

        xuatNV.setBackground(new java.awt.Color(13, 255, 0));
        xuatNV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        xuatNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlythuvien/icon/if_output-1_2916359.png"))); // NOI18N
        xuatNV.setText("Xuất File");
        xuatNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xuatNVActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Tìm Kiếm: ");

        timKiem.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        nhap.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        nhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlythuvien/icon/if_import-download-save_2931171.png"))); // NOI18N
        nhap.setText("Nhập File");
        nhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapActionPerformed(evt);
            }
        });

        AddToDB.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        AddToDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlythuvien/icon/add dâtbase.png"))); // NOI18N
        AddToDB.setText("Thêm Vào CSDL");
        AddToDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToDBActionPerformed(evt);
            }
        });

        seeAll.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        seeAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlythuvien/icon/see.png"))); // NOI18N
        seeAll.setText("Hiện Thị Tất Cả");
        seeAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeAllActionPerformed(evt);
            }
        });

        jDesktopPane2.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(maNV, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(tenNV, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(ngaySinh, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(gT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(diaChi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(email, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(sDT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(comboTimKiem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(xuatNV, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(timKiem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(nhap, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(AddToDB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(seeAll, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                .addComponent(comboTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(xuatNV))
                            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jButton1))
                                .addGap(39, 39, 39)
                                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gT, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maNV, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane2Layout.createSequentialGroup()
                                            .addComponent(jButton2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(sDT, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1076, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                        .addComponent(nhap)
                        .addGap(173, 173, 173)
                        .addComponent(AddToDB)
                        .addGap(115, 115, 115)
                        .addComponent(seeAll)
                        .addGap(102, 102, 102))))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maNV, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(25, 25, 25)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(gT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(27, 27, 27)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(27, 27, 27)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sDT, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addGap(83, 83, 83)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)))
                .addGap(8, 8, 8)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seeAll, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nhap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddToDB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xuatNV, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jDesktopPane2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {diaChi, email, gT, maNV, ngaySinh, sDT, tenNV});

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.addTab("Cập Nhật & Tìm Kiếm", jPanel3);

        TKNV.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        TKNV.setForeground(new java.awt.Color(255, 255, 255));
        TKNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TKNV.setText("Thống Kê Nhân Viên");
        TKNV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TKNV.setVerifyInputWhenFocusTarget(false);
        TKNV.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        Table2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Table2.setRowHeight(26);
        jScrollPane3.setViewportView(Table2);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlythuvien/icon/statistic.png"))); // NOI18N
        jButton7.setText("Theo Địa Chỉ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlythuvien/icon/statistic.png"))); // NOI18N
        jButton8.setText("Theo Giới Tính");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlythuvien/icon/statistic.png"))); // NOI18N
        jButton9.setText("Theo Năm Sinh");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("GVHD: ThS. LÊ THỊ HOA");

        jButton10.setBackground(new java.awt.Color(13, 255, 0));
        jButton10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlythuvien/icon/if_output-1_2916359.png"))); // NOI18N
        jButton10.setText("Xuất File");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(TKNV, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TKNV, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(67, 67, 67)
                        .addComponent(jButton10)
                        .addGap(17, 17, 17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1087, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(TKNV, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton7)
                        .addGap(38, 38, 38)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thống Kê", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 832, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*------------------------ init() ------------------------------------------*/
    // Xóa Tất Cả các dòng
    public void removeAllRow() {
        DefaultTableModel modelDelete = (DefaultTableModel) Table1.getModel();
        modelDelete.setRowCount(0);
        if (modelDelete.getRowCount() != 0) {
            modelDelete.setRowCount(0);
        }
    }

    public ArrayList<NhanVien> getListNV() {          //Đọc dữ liệu trong database
        ArrayList<NhanVien> nhanVien = new ArrayList<NhanVien>();
        String sql = "SELECT * FROM nhanvien";

        try {
            ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                //         , , , , , , 
                NhanVien nv = new NhanVien();
                nv.setMaNV(rs.getString("MaNV_LDP"));
                nv.setTenNV(rs.getString("TenNV_LDP"));
                nv.setNgaySinh(rs.getString("NgaySinh_LDP"));
                nv.setGT(rs.getString("GT_LDP"));
                nv.setDiaChi(rs.getString("DiaChi_LDP"));
                nv.setEmail(rs.getString("Email_LDP"));
                nv.setSDT(rs.getString("SDT_LDP"));
                nhanVien.add(nv);    //thêm vào mảng
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
        return nhanVien;
    }

    public void showTable(ArrayList<NhanVien> nhanVien) {
        for (NhanVien nv : nhanVien) {
            model.addRow(new Object[]{
                nv.getMaNV(), nv.getTenNV(), nv.getNgaySinh(), nv.getGT(), nv.getDiaChi(), nv.getEmail(), nv.getSDT()
            });
        }
    }

    /*--------------------------------------------- Chức Năng Cập Nhật ----------------------------------------*/
    public void clearData() {
        maNV.setText("");
        tenNV.setText("");
        ngaySinh.setText("");
        gT.setText("");
        diaChi.setText("");
        email.setText("");
        sDT.setText("");
    }

    public boolean addNV(NhanVien nv) {               //Thêm sách vào database
        String sql = "INSERT INTO `quanlythuvien`.`nhanvien` (`MaNV_LDP`, `TenNV_LDP`,"
                + " `NgaySinh_LDP`, `GT_LDP`, `DiaChi_LDP`, `Email_LDP`, `SDT_LDP`) "
                + "VALUES (?,?,?,?,?,?,?);";
        try {
            ps = conn.prepareStatement(sql);
            ps.setString(1, nv.getMaNV());
            ps.setString(2, nv.getTenNV());
            ps.setString(3, nv.getNgaySinh());
            ps.setString(4, nv.getGT());
            ps.setString(5, nv.getDiaChi());
            ps.setString(6, nv.getEmail());
            ps.setString(7, nv.getSDT());

            int kt = ps.executeUpdate();
            if (kt != 0) {
                JOptionPane.showMessageDialog(null, "Bạn đã thêm dữ liệu thành công !");
                return true;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
        return false;
    }

    // update database
    public boolean update() {
        String sql = "UPDATE `quanlythuvien`.`nhanvien` "
                + "SET `MaNV_LDP` = ?, `TenNV_LDP` = ?, "
                + "`NgaySinh_LDP` = ?, `GT_LDP` = ?, "
                + "`DiaChi_LDP` = ?, `Email_LDP` = ?, "
                + "`SDT_LDP` = ? "
                + "WHERE (`MaNV_LDP` = ?);";
        try {
            ps = conn.prepareStatement(sql);
            ps.setString(1, maNV.getText());
            ps.setString(2, tenNV.getText());
            ps.setString(3, ngaySinh.getText());
            ps.setString(4, gT.getText());
            ps.setString(5, diaChi.getText());
            ps.setString(6, email.getText());
            ps.setString(7, sDT.getText());
            ps.setString(8, (Table1.getValueAt(Table1.getSelectedRow(), 0)).toString());

            int kt = ps.executeUpdate();
            if (kt != 0) {
                JOptionPane.showMessageDialog(null, "Bạn đã cập nhật dữ liệu thành công");
                //  Xóa dòng tại vị trí rowID lấy từ action mouse click
                model.removeRow(rowID);
                //  Thêm bản ghi vào bảng tại vị trí rowID lấy từ action event mouse click
                model.insertRow(rowID, new Object[]{
                    maNV.getText(), tenNV.getText(), ngaySinh.getText(), gT.getText(),
                    diaChi.getText(), email.getText(), sDT.getText()
                });
                clearData();
                return true;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }

        return false;
    }

    public boolean remove() {                       //Xóa Sách khỏi database
        String sql = "DELETE FROM NHANVIEN WHERE MaNV_LDP = ?;";
        try {
            ps = conn.prepareStatement(sql);
            ps.setString(1, maNV.getText());
            int kt = ps.executeUpdate();
            if (kt != 0) {
                JOptionPane.showMessageDialog(null, "Bạn đã xóa dữ liệu thành công !");
                //  Xóa dòng tại vị trí rowID với rowID lấy từ action mouse click
                return true;
            }
        } catch (SQLException ex) {
//            Logger.getLogger(QuanLySach.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error => " + ex.getMessage());
        }
        return false;
    }

    /*------------------------------------------------- Tìm Kiếm ---------------------------------------------*/
    //Tìm kiếm sách theo mã sách
    public ArrayList<NhanVien> tKTheoMaNV() {
        ArrayList<NhanVien> nhanVien = new ArrayList<NhanVien>();
        String sql = "SELECT * FROM NHANVIEN WHERE (MaNV_LDP = '" + timKiem.getText() + "');";

        try {
            ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                NhanVien nv = new NhanVien();
                nv.setMaNV(rs.getString("MaNV_LDP"));
                nv.setTenNV(rs.getString("TenNV_LDP"));
                nv.setNgaySinh(rs.getString("NgaySinh_LDP"));
                nv.setGT(rs.getString("GT_LDP"));
                nv.setDiaChi(rs.getString("DiaChi_LDP"));
                nv.setEmail(rs.getString("Email_LDP"));
                nv.setSDT(rs.getString("SDT_LDP"));
                nhanVien.add(nv);    //thêm vào mảng
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
        return nhanVien;
    }

    //Tìm kiếm sách theo tên sách
    public ArrayList<NhanVien> tKTheoTenNV() {
        ArrayList<NhanVien> nhanVien = new ArrayList<NhanVien>();
        String sql = "SELECT * FROM NHANVIEN"
                + " Where TenNV_LDP LIKE '%" + timKiem.getText() + "%';";

        try {
            ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                NhanVien nv = new NhanVien();
                nv.setMaNV(rs.getString("MaNV_LDP"));
                nv.setTenNV(rs.getString("TenNV_LDP"));
                nv.setNgaySinh(rs.getString("NgaySinh_LDP"));
                nv.setGT(rs.getString("GT_LDP"));
                nv.setDiaChi(rs.getString("DiaChi_LDP"));
                nv.setEmail(rs.getString("Email_LDP"));
                nv.setSDT(rs.getString("SDT_LDP"));
                nhanVien.add(nv);    //thêm vào mảng
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
        return nhanVien;
    }

    //Tìm kiếm sách theo Thể loại
    public ArrayList<NhanVien> tKTheoDiaChi() {
        ArrayList<NhanVien> nhanVien = new ArrayList<NhanVien>();
        String sql = "SELECT * FROM NHANVIEN"
                + " Where DiaChi_LDP LIKE '%" + timKiem.getText() + "%';";

        try {
            ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                NhanVien nv = new NhanVien();
                nv.setMaNV(rs.getString("MaNV_LDP"));
                nv.setTenNV(rs.getString("TenNV_LDP"));
                nv.setNgaySinh(rs.getString("NgaySinh_LDP"));
                nv.setGT(rs.getString("GT_LDP"));
                nv.setDiaChi(rs.getString("DiaChi_LDP"));
                nv.setEmail(rs.getString("Email_LDP"));
                nv.setSDT(rs.getString("SDT_LDP"));
                nhanVien.add(nv);    //thêm vào mảng
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
        return nhanVien;
    }

    //Tìm kiếm sách theo tên tác giả
    public ArrayList<NhanVien> tKTheoEmail() {
        ArrayList<NhanVien> nhanVien = new ArrayList<NhanVien>();
        String sql = "SELECT * FROM NHANVIEN"
                + " Where Email_LDP LIKE '%" + timKiem.getText() + "%';";

        try {
            ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                NhanVien nv = new NhanVien();
                nv.setMaNV(rs.getString("MaNV_LDP"));
                nv.setTenNV(rs.getString("TenNV_LDP"));
                nv.setNgaySinh(rs.getString("NgaySinh_LDP"));
                nv.setGT(rs.getString("GT_LDP"));
                nv.setDiaChi(rs.getString("DiaChi_LDP"));
                nv.setEmail(rs.getString("Email_LDP"));
                nv.setSDT(rs.getString("SDT_LDP"));
                nhanVien.add(nv);    //thêm vào mảng
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
        return nhanVien;
    }

    //Tìm kiếm sách theo Nhà Xuất Bản
    public ArrayList<NhanVien> tKTheoSDT() {
        ArrayList<NhanVien> nhanVien = new ArrayList<NhanVien>();
        String sql = "SELECT * FROM NHANVIEN"
                + " Where SDT_LDP LIKE '%" + Integer.parseInt(timKiem.getText()) + "%';";

        try {
            ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                NhanVien nv = new NhanVien();
                nv.setMaNV(rs.getString("MaNV_LDP"));
                nv.setTenNV(rs.getString("TenNV_LDP"));
                nv.setNgaySinh(rs.getString("NgaySinh_LDP"));
                nv.setGT(rs.getString("GT_LDP"));
                nv.setDiaChi(rs.getString("DiaChi_LDP"));
                nv.setEmail(rs.getString("Email_LDP"));
                nv.setSDT(rs.getString("SDT_LDP"));
                nhanVien.add(nv);    //thêm vào mảng
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
        return nhanVien;
    }


    /*------------------------------------------------- Thống Kê ---------------------------------------------*/
    public void removeAllRowTKe() {
        DefaultTableModel modelDelete = (DefaultTableModel) Table2.getModel();
        modelDelete.setRowCount(0);
        if (modelDelete.getRowCount() != 0) {
            modelDelete.setRowCount(0);
        }
    }

    //Hàm thống kê Sách theo Tên Sách
    public ArrayList<NhanVien> tKeTheoTenNV() {
        ArrayList<NhanVien> nhanVien = new ArrayList<NhanVien>();
        String sql = "SELECT TenNV_LDP, Count(TenNV_LDP) "
                + "FROM quanlythuvien.nhanvien "
                + "GROUP BY TenNV_LDP;";
        try {
            ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                NhanVien nv = new NhanVien();
                nv.setTenNV(rs.getString("TenNV_LDP"));
                nv.setSoLuong(rs.getInt("Count(TenNV_LDP)"));
                nhanVien.add(nv);    //thêm vào mảng
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
        return nhanVien;
    }

    //Hàm thống kê sách theo Thể Loại
    public ArrayList<NhanVien> tKeTheoGT() {
        ArrayList<NhanVien> nhanVien = new ArrayList<NhanVien>();
        String sql = "Select TheLoai_LDP,Sum(SoLuongCon_LDP),Sum(TongSoLuong_LDP) "
                + "from quanlythuvien.sach "
                + "group by TheLoai_LDP;";
        try {
            ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                NhanVien nv = new NhanVien();
                //nv.setTheLoai(rs.getString("TheLoai_LDP"));
                //nv.setSoLuongCon(rs.getInt("Sum(SoLuongCon_LDP)"));
                //nv.setTongSoLuong(rs.getInt("Sum(TongSoLuong_LDP)"));
                nhanVien.add(nv);    //thêm vào mảng
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
        return nhanVien;
    }

    //Hàm thống kê sách theo Nhà Xuất Bản
    public ArrayList<Sach> tKeTheoNXB() {
        ArrayList<Sach> sach = new ArrayList<Sach>();
        String sql = "Select NXB_LDP,Sum(SoLuongCon_LDP),Sum(TongSoLuong_LDP) "
                + "from quanlythuvien.sach "
                + "group by NXB_LDP;";
        try {
            ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                Sach s = new Sach();
                s.setTheLoai(rs.getString("NXB_LDP"));
                s.setSoLuongCon(rs.getInt("Sum(SoLuongCon_LDP)"));
                s.setTongSoLuong(rs.getInt("Sum(TongSoLuong_LDP)"));
                sach.add(s);    //thêm vào mảng
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
        return sach;
    }
    private void gTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gTActionPerformed

    private void diaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaChiActionPerformed

    private void comboTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTimKiemActionPerformed
        fileOut = false;
        ArrayList<NhanVien> nhanVien = new ArrayList<NhanVien>();
        Object obj = evt.getSource();
        if (obj == comboTimKiem) {
            int index = comboTimKiem.getSelectedIndex();
            switch (index) {
                case 0:
                    nhanVien = tKTheoMaNV();
                    break;
                case 1:
                    nhanVien = tKTheoTenNV();
                    break;
                case 2:
                    nhanVien = tKTheoDiaChi();
                    break;
                case 3:
                    nhanVien = tKTheoEmail();
                    break;
                case 4:
                    nhanVien = tKTheoSDT();
                    break;
            }
            removeAllRow();
            showTable(nhanVien);
        }
    }//GEN-LAST:event_comboTimKiemActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        removeAllRowTKe();
        TKNV.setText("Thống Kê Nhân Viên Theo Địa Chỉ");
        DefaultTableModel modelTK = (DefaultTableModel) Table2.getModel();
        modelTK.setColumnIdentifiers(new Object[]{
            "         STT", "         Địa Chỉ", "         Số Lượng"
        });
        int i = 0;
        String sql = "select diachi_LDP , count(DiaChi_LDP) \n"
                + "from quanlythuvien.nhanvien\n"
                + "group by DiaChi_LDP";
        try {
            ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                modelTK.addRow(new Object[]{
                    ++i, rs.getString(1), rs.getString(2)
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyDocGia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        removeAllRowTKe();
        TKNV.setText("Thống Kê Nhân Viên Theo Giới Tính");
        DefaultTableModel modelTK = (DefaultTableModel) Table2.getModel();
        modelTK.setColumnIdentifiers(new Object[]{
            "         STT", "         Giới Tính", "         Số Lượng"
        });
        int i = 0;
        String sql = "select GT_LDP , count(GT_LDP) \n"
                + "from quanlythuvien.nhanvien\n"
                + "group by GT_LDP";
        try {
            ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                modelTK.addRow(new Object[]{
                    ++i, rs.getString(1), rs.getString(2)
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyDocGia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        removeAllRowTKe();
        TKNV.setText("Thống Kê Nhân Viên Theo Năm Sinh");
        DefaultTableModel modelTK = (DefaultTableModel) Table2.getModel();
        modelTK.setColumnIdentifiers(new Object[]{
            "         STT", "         Năm Sinh", "         Số Lượng"
        });
        int i = 0;
        String sql = "Select YEAR(NgaySinh_LDP),count(YEAR(NgaySinh_LDP))\n"
                + "from quanlythuvien.nhanvien\n"
                + "group by YEAR(NgaySinh_LDP);";
        try {
            ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                modelTK.addRow(new Object[]{
                    ++i, rs.getString(1), rs.getString(2)
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyDocGia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton9ActionPerformed


    private void xuatNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xuatNVActionPerformed
        String f0 = System.getProperty("user.home");
        String f1 = "\\Documents\\NetBeansProjects\\Quanlythuvien\\Quản Lý Nhân Viên\\";
        String f2 = null;
        if (fileOut == true) {
            f2 = "Thông Tin Nhân Viên.docx";
        } else {
            if (comboTimKiem.getSelectedItem().equals("Tìm Kiếm Theo Mã Nhân Viên")) {
                f2 = "Tìm Kiếm Theo Mã Nhân Viên.docx";
            } else if (comboTimKiem.getSelectedItem().equals("Tìm Kiếm Theo Tên Nhân Viên")) {
                f2 = "Tìm Kiếm Theo Tên Nhân Viên.docx";
            } else if (comboTimKiem.getSelectedItem().equals("Tìm Kiếm Theo Địa Chỉ")) {
                f2 = "Tìm Kiếm Theo Địa Chỉ.docx";
            } else if (comboTimKiem.getSelectedItem().equals("Tìm Kiếm Theo Email")) {
                f2 = "Tìm Kiếm Theo Email.docx";
            } else {
                f2 = "Tìm Kiếm Theo SĐT.docx";
            }
        }
        String fileName = f0 + f1 + f2;

        try {
            InputStream file = new FileInputStream(fileName);
            XWPFDocument hdoc = new XWPFDocument(OPCPackage.open(file));
            Iterator bodyElementIterator = hdoc.getBodyElementsIterator();
            for (XWPFParagraph p : hdoc.getParagraphs()) {
                List<XWPFRun> runs = p.getRuns();
                if (runs != null) {
                    for (XWPFRun r : runs) {
                        r.setFontSize(12);
                        r.setFontFamily("Times New Roman");
                        String text = r.getText(0);
                        if (text != null && text.contains("ngayxxx")) {
                            SimpleDateFormat day = new SimpleDateFormat("dd");
                            SimpleDateFormat month = new SimpleDateFormat("MM");
                            SimpleDateFormat year = new SimpleDateFormat("yyyy");
                            Date date = new Date();
                            String ngay = day.format(date);
                            String thang = month.format(date);
                            String nam = year.format(date);
                            text = text.replace("ngayxxx", "Ngày  " + ngay + "  tháng  " + thang + "  năm  " + nam);
                            r.setText(text, 0);
                            break;
                        }
                    }
                }
            }
            while (bodyElementIterator.hasNext()) {
                IBodyElement element = (IBodyElement) bodyElementIterator.next();
                if ("TABLE".equalsIgnoreCase(element.getElementType().name())) {
                    //Danh sách tất cả Table trong file word
                    List<XWPFTable> tableList = element.getBody().getTables();
                    //Duyệt qua danh sách tất cả các table
                    for (XWPFTable table : tableList) {
                        //Căn bảng ở giữa file
                        table.setTableAlignment(TableRowAlign.CENTER);
                        //  Xóa các dòng thừa trước khi thêm mới
                        while (table.getRow(1) != null) {
                            table.removeRow(1);
                        }
                        //Thêm các dòng từ jTable vào table trong word
                        for (int i = 1; i <= Table1.getRowCount(); i++) {
                            XWPFTableRow newRow = table.createRow();
                            for (int j = 0; j < table.getRow(i).getTableCells().size(); j++) {
                                newRow.getCell(j).setText(Table1.getValueAt(i - 1, j).toString());
                            }
                        }
                    }
                }
            }
            OutputStream out = new FileOutputStream(f2);
            hdoc.write(out);
            out.close();
        } catch (IOException | InvalidFormatException ex) {
            Logger.getLogger(QuanLyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }

        //Mở file
        try {
            File myFile = new File(f0 + "\\Documents\\NetBeansProjects\\Quanlythuvien\\" + f2);
            Desktop.getDesktop().open(myFile);
        } catch (IOException ex) {
            // no application registered for PDFs
            ex.printStackTrace();
        }
    }//GEN-LAST:event_xuatNVActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int choose = JOptionPane.showConfirmDialog(null, "Bạn có muốn thay đổi dữ liệu không ?",
                "Quản Lý Nhân Viên _ Sửa", JOptionPane.YES_NO_OPTION);
        if (choose == 0) {
            boolean flag = update();
            if (flag) {
                clearData();
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int choose = JOptionPane.showConfirmDialog(null, "Bạn có muốn thay xóa thông tin nhân viên không ?",
                "Quản Lý Nhân Viên _ Xóa", JOptionPane.YES_NO_OPTION);
        if (choose == 0) {
            boolean flag = remove();
            if (flag) {
                clearData();
                //  Xóa dòng tại vị trí rowID lấy từ action mouse click
                model.removeRow(rowID);
            }
        } else {
            clearData();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1MouseClicked
        rowID = Table1.getSelectedRow();
        maNV.setText(Table1.getValueAt(rowID, 0).toString());
        tenNV.setText(Table1.getValueAt(rowID, 1).toString());
        ngaySinh.setText(Table1.getValueAt(rowID, 2).toString());
        gT.setText(Table1.getValueAt(rowID, 3).toString());
        diaChi.setText(Table1.getValueAt(rowID, 4).toString());
        email.setText(Table1.getValueAt(rowID, 5).toString());
        sDT.setText(Table1.getValueAt(rowID, 6).toString());
    }//GEN-LAST:event_Table1MouseClicked

    private void ngaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ngaySinhActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NhanVien nv = new NhanVien();
        nv.setMaNV(maNV.getText());
        nv.setTenNV(tenNV.getText());
        nv.setNgaySinh(ngaySinh.getText());
        nv.setGT(gT.getText());
        nv.setDiaChi(diaChi.getText());
        nv.setEmail(email.getText());
        nv.setSDT(sDT.getText());
        boolean flag = addNV(nv);                         //Nếu thêm sách thành công
        if (flag) {
            model.addRow(new Object[]{
                nv.getMaNV(), nv.getTenNV(), nv.getNgaySinh(), nv.getGT(), nv.getDiaChi(),
                nv.getEmail(), nv.getSDT()
            });
            clearData();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapActionPerformed
        // chỗ này sẽ delete hết các dòng trước khi nhập dữ liệu từ file
        removeAllRow();
        // đường dẫn
        String path = null;
        JFileChooser fileChooser = new JFileChooser();
        // show ra một bảng chọn file
        int rVal = fileChooser.showOpenDialog(null);
        // nếu nhấn nút ok (tuỳ chọn APPROVE_OPTION)
        if (rVal == JFileChooser.APPROVE_OPTION) {
            String fileName = fileChooser.getSelectedFile().getName();
            String dir = fileChooser.getCurrentDirectory().toString();
            path = dir + "\\" + fileName;
        } // nếu nhấn nút cancel trong bảng
        else if (rVal == JFileChooser.CANCEL_OPTION) {
            return;
        }
        // vector lưu tên cột
        Vector columns = new Vector();
        try {
            FileInputStream file = new FileInputStream(new File(path));
            // tạo một file excel
            XSSFWorkbook workbook = new XSSFWorkbook(file);
            // tạo một sheet trong excel có số thứ tự là 0
            XSSFSheet sheet = workbook.getSheetAt(0);
            // con trỏ duyệt hàng trong excel
            Iterator<Row> rowIt = sheet.iterator();
            // nếu vẫn còn dòng trong file
            while (rowIt.hasNext()) {
                // tạo một dòng mới
                Row row = rowIt.next();
                // con trỏ trỏ vào các ô trong một dòng
                Iterator<Cell> cellIt = row.cellIterator();
                // nếu là hàng 0 bỏ qua
                if (row.getRowNum() != 0) {
                    //vector chứa dữ liệu trong 1 dòng để add vào bảng jtabel
                    Vector<String> rowData = new Vector<String>();
                    // nếu vẫn còn ô tiếp theo
                    while (cellIt.hasNext()) {
                        // lấy cell trong bảng excel
                        Cell cell = cellIt.next();
                        if (cell.getCellType() == CellType.STRING) {
                            rowData.add(cell.getStringCellValue().toString());
                        } else if (DateUtil.isCellDateFormatted(cell)) {
                            // Format Date
                            String pattern = "yyyy-MM-dd";
                            SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
                            // Format cell.getDateCellValue()
                            String date = simpleDateFormat.format(cell.getDateCellValue());
                            rowData.add(date);
                        } // nếu cell có kiểu dữ liệu là số thì chuyển thành xâu.
                        else if (cell.getCellType() == CellType.NUMERIC) {
                            rowData.add(NumberToTextConverter.toText(cell.getNumericCellValue()));
                        }
                    }
                    // add dữ liệu vào trong bảng jtable
                    model.addRow(rowData);
                }
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(QuanLySach.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(QuanLySach.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nhapActionPerformed

    private void AddToDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToDBActionPerformed
        //      System.out.println(Table1.getRowCount());
        NhanVien nv = new NhanVien();
        int n = Table1.getRowCount();
        String sql = "INSERT INTO `quanlythuvien`.`nhanvien` (`MaNV_LDP`, `TenNV_LDP`,"
                + " `NgaySinh_LDP`, `GT_LDP`, `DiaChi_LDP`, `Email_LDP`, `SDT_LDP`) "
                + "VALUES (?,?,?,?,?,?,?);";
        for (int index = 0; index < n; index++) {
            nv.setMaNV(Table1.getValueAt(index, 0).toString());
            nv.setTenNV(Table1.getValueAt(index, 1).toString());
            nv.setNgaySinh(Table1.getValueAt(index, 2).toString());
            nv.setGT(Table1.getValueAt(index, 3).toString());
            nv.setDiaChi(Table1.getValueAt(index, 4).toString());
            nv.setEmail((Table1.getValueAt(index, 5).toString()));
            nv.setSDT(Table1.getValueAt(index, 6).toString());
            try {
                ps = conn.prepareStatement(sql);
                ps.setString(1, nv.getMaNV());
                ps.setString(2, nv.getTenNV());
                ps.setString(3, nv.getNgaySinh());
                ps.setString(4, nv.getGT());
                ps.setString(5, nv.getDiaChi());
                ps.setString(6, nv.getEmail());
                ps.setString(7, nv.getSDT());

                int kt = ps.executeUpdate();
                if (kt != 0) {
                    // Dòng bắt đầu đếm từ 0 nhưng cột lại bắt đàu đếm từ 0
                    model.removeRow(index);
                    n--;
                    index--;
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error ! " + ex.getMessage()
                        + " \". Hãy sửa trực tiếp trên bảng và ấn \"Thêm vào CSDL\" để tiếp tục thêm.");
            }
        }
    }//GEN-LAST:event_AddToDBActionPerformed

    private void seeAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeAllActionPerformed
        fileOut = true;
        removeAllRow();
        clearData();
        showTable(getListNV());
    }//GEN-LAST:event_seeAllActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String f0 = System.getProperty("user.home");
        String f1 = "\\Documents\\NetBeansProjects\\Quanlythuvien\\Quản Lý Nhân Viên\\";
        String f2 = null;
        if (TKNV.getText().equals("Thống Kê Nhân Viên Theo Địa Chỉ")) {
            f2 = "Thống Kê Theo Địa Chỉ.docx";
        } else if (TKNV.getText().equals("Thống Kê Nhân Viên Theo Giới Tính")) {
            f2 = "Thống Kê Theo Giới Tính.docx";
        } else if (TKNV.getText().equals("Thống Kê Nhân Viên Theo Năm Sinh")) {
            f2 = "Thống Kê Theo Năm Sinh.docx";
        }
        String fileName = f0 + f1 + f2;

      try {
            InputStream file = new FileInputStream(fileName);
            XWPFDocument docx = new XWPFDocument(OPCPackage.open(file));
            Iterator bodyElementIterator = docx.getBodyElementsIterator();
            for (XWPFParagraph p : docx.getParagraphs()) {
                List<XWPFRun> runs = p.getRuns();
                if (runs != null) {
                    for (XWPFRun r : runs) {
                        r.setFontSize(12);
                        r.setFontFamily("Times New Roman");
                        String text = r.getText(0);
                        if (text != null && text.contains("ngayxxx")) {
                            SimpleDateFormat day = new SimpleDateFormat("dd");
                            SimpleDateFormat month = new SimpleDateFormat("MM");
                            SimpleDateFormat year = new SimpleDateFormat("yyyy");
                            Date date = new Date();
                            String ngay = day.format(date);
                            String thang = month.format(date);
                            String nam = year.format(date);
                            text = text.replace("ngayxxx", "Ngày  " + ngay + "  tháng  " + thang + "  năm  " + nam);
                            r.setText(text, 0);
                            break;
                        }
                    }
                }
            }
            while (bodyElementIterator.hasNext()) {
                IBodyElement element = (IBodyElement) bodyElementIterator.next();
                if ("TABLE".equalsIgnoreCase(element.getElementType().name())) {
                    //Danh sách tất cả Table trong file word
                    List<XWPFTable> tableList = element.getBody().getTables();

                    //Duyệt qua danh sách tất cả các table
                    for (XWPFTable table : tableList) {
                        //Căn bảng ở giữa file
                        table.setTableAlignment(TableRowAlign.CENTER);
                        //  Xóa các dòng thừa trước khi thêm mới
                        while (table.getRow(1) != null) {
                            table.removeRow(1);
                        }
                        //Thêm các dòng từ jTable vào table trong word
                        for (int i = 1; i <= Table2.getRowCount(); i++) {
                            XWPFTableRow newRow = table.createRow();
                            for (int j = 0; j < table.getRow(i).getTableCells().size(); j++) {
                                newRow.getCell(j).setText(Table2.getValueAt(i - 1, j).toString());
                            }
                        }
                    }
                }
            }
            OutputStream out = new FileOutputStream(f2);
            docx.write(out);
            out.close();
        } catch (IOException | InvalidFormatException ex) {
            Logger.getLogger(QuanLyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }

        //Mở file
        try {
            File myFile = new File(f0 + "\\Documents\\NetBeansProjects\\Quanlythuvien\\" + f2);
            Desktop.getDesktop().open(myFile);
        } catch (IOException ex) {
            // no application registered for PDFs
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToDB;
    private javax.swing.JLabel TKNV;
    private javax.swing.JTable Table1;
    private javax.swing.JTable Table2;
    private javax.swing.JComboBox<String> comboTimKiem;
    private javax.swing.JTextField diaChi;
    private javax.swing.JTextField email;
    private javax.swing.JTextField gT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField maNV;
    private javax.swing.JTextField ngaySinh;
    private javax.swing.JButton nhap;
    private javax.swing.JTextField sDT;
    private javax.swing.JButton seeAll;
    private javax.swing.JTextField tenNV;
    private javax.swing.JTextField timKiem;
    private javax.swing.JButton xuatNV;
    // End of variables declaration//GEN-END:variables
}
